/*
 * This file was automatically generated by EvoSuite
 * Mon May 15 01:32:45 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;


import java.util.Collection;
import java.util.GregorianCalendar;
import java.util.LinkedList;

import org.junit.runner.RunWith;

public class TimeTable_ESTest  {

  //Test case number: 0
  /*
   * 40 covered goals:
   * Goal 1. edu.osu.cs362.TimeTable.<init>()V: root-Branch
   * Goal 2. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I3 Branch 10 IFNULL L127 - false
   * Goal 3. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I5 Branch 11 IFNONNULL L127 - true
   * Goal 4. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I14 Branch 12 IFNE L130 - true
   * Goal 5. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I27 Branch 13 IF_ICMPGE L136 - false
   * Goal 6. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I40 Branch 14 IFEQ L138 - false
   * Goal 7. Branch edu.osu.cs362.TimeTable.<init>()V: root-Branch in context: edu.osu.cs362.TimeTable:<init>()V
   * Goal 8. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I5 Branch 11 IFNONNULL L127 - true in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 9. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I3 Branch 10 IFNULL L127 - false in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 10. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I14 Branch 12 IFNE L130 - true in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 11. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I27 Branch 13 IF_ICMPGE L136 - false in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 12. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I40 Branch 14 IFEQ L138 - false in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 13. [Output]: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:NonNull:java.util.LinkedList:size()I:Positive
   * Goal 14. edu.osu.cs362.TimeTable.<init>()V: Line 27
   * Goal 15. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 127
   * Goal 16. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 130
   * Goal 17. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 136
   * Goal 18. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 137
   * Goal 19. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 138
   * Goal 20. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 139
   * Goal 21. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 140
   * Goal 22. [METHOD] edu.osu.cs362.TimeTable.<init>()V
   * Goal 23. [METHOD] edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 24. [METHODNOEX] edu.osu.cs362.TimeTable.<init>()V
   * Goal 25. [METHODNOEX] edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 26. Weak Mutation 63: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:127 - ReplaceComparisonOperator = null -> != null
   * Goal 27. Weak Mutation 64: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:127 - ReplaceComparisonOperator != null -> = null
   * Goal 28. Weak Mutation 65: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:130 - ReplaceComparisonOperator != -> ==
   * Goal 29. Weak Mutation 66: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - ReplaceConstant - 0 -> 1
   * Goal 30. Weak Mutation 67: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - InsertUnaryOp Negation of i
   * Goal 31. Weak Mutation 68: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - InsertUnaryOp IINC 1 i
   * Goal 32. Weak Mutation 69: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - InsertUnaryOp IINC -1 i
   * Goal 33. Weak Mutation 70: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - ReplaceComparisonOperator >= -> -1
   * Goal 34. Weak Mutation 73: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:137 - InsertUnaryOp Negation of i
   * Goal 35. Weak Mutation 74: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:137 - InsertUnaryOp IINC 1 i
   * Goal 36. Weak Mutation 75: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:137 - InsertUnaryOp IINC -1 i
   * Goal 37. Weak Mutation 78: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:138 - ReplaceComparisonOperator == -> !=
   * Goal 38. Weak Mutation 79: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:139 - InsertUnaryOp Negation of i
   * Goal 39. Weak Mutation 80: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:139 - InsertUnaryOp IINC 1 i
   * Goal 40. Weak Mutation 81: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:139 - InsertUnaryOp IINC -1 i
   */

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TimeTable timeTable0 = new TimeTable();
      GregorianCalendar mockGregorianCalendar0 = new GregorianCalendar();
      CalDay calDay0 = new CalDay((GregorianCalendar) mockGregorianCalendar0);
      LinkedList<Appt> linkedList0 = calDay0.appts;
      Appt appt0 = new Appt(2, 1, 1, 1, (-351), "\t", "\t");
      linkedList0.add(appt0);
      linkedList0.addAll((Collection<? extends Appt>) linkedList0);
      timeTable0.deleteAppt(linkedList0, appt0);
      assertEquals(1, linkedList0.size());
      assertEquals(1, calDay0.getSizeAppts());
  }

  //Test case number: 1
  /*
   * 39 covered goals:
   * Goal 1. edu.osu.cs362.TimeTable.<init>()V: root-Branch
   * Goal 2. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I11 Branch 1 IFNE L43 - true
   * Goal 3. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I43 Branch 2 IFEQ L51 - false
   * Goal 4. Branch edu.osu.cs362.TimeTable.<init>()V: root-Branch in context: edu.osu.cs362.TimeTable:<init>()V
   * Goal 5. Branch edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I11 Branch 1 IFNE L43 - true in context: edu.osu.cs362.TimeTable:getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 6. Branch edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I43 Branch 2 IFEQ L51 - false in context: edu.osu.cs362.TimeTable:getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 7. getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;_org.evosuite.runtime.TooManyResourcesException_IMPLICIT
   * Goal 8. edu.osu.cs362.TimeTable.<init>()V: Line 27
   * Goal 9. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 40
   * Goal 10. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 43
   * Goal 11. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 50
   * Goal 12. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 51
   * Goal 13. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 52
   * Goal 14. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 53
   * Goal 15. [METHOD] edu.osu.cs362.TimeTable.<init>()V
   * Goal 16. [METHOD] edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 17. [METHODNOEX] edu.osu.cs362.TimeTable.<init>()V
   * Goal 18. Weak Mutation 0: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:43 - ReplaceVariable firstDay -> lastDay
   * Goal 19. Weak Mutation 1: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:43 - ReplaceVariable lastDay -> firstDay
   * Goal 20. Weak Mutation 2: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:43 - ReplaceComparisonOperator != -> ==
   * Goal 21. Weak Mutation 5: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:50 - ReplaceVariable firstDay -> lastDay
   * Goal 22. Weak Mutation 6: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:51 - ReplaceVariable nextDay -> firstDay
   * Goal 23. Weak Mutation 7: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:51 - ReplaceVariable nextDay -> lastDay
   * Goal 24. Weak Mutation 8: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:51 - ReplaceVariable lastDay -> firstDay
   * Goal 25. Weak Mutation 9: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:51 - ReplaceVariable lastDay -> nextDay
   * Goal 26. Weak Mutation 10: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:51 - ReplaceComparisonOperator == -> !=
   * Goal 27. Weak Mutation 11: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:52 - ReplaceVariable calDays -> appts
   * Goal 28. Weak Mutation 12: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:52 - ReplaceVariable nextDay -> firstDay
   * Goal 29. Weak Mutation 13: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:52 - ReplaceVariable nextDay -> lastDay
   * Goal 30. Weak Mutation 14: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceVariable nextDay -> firstDay
   * Goal 31. Weak Mutation 15: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceVariable nextDay -> lastDay
   * Goal 32. Weak Mutation 16: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceVariable nextDay -> firstDay
   * Goal 33. Weak Mutation 17: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceVariable nextDay -> lastDay
   * Goal 34. Weak Mutation 18: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 5 -> 0
   * Goal 35. Weak Mutation 19: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 5 -> 1
   * Goal 36. Weak Mutation 20: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 5 -> -1
   * Goal 37. Weak Mutation 21: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 5 -> 4
   * Goal 38. Weak Mutation 22: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 5 -> 6
   * Goal 39. Weak Mutation 23: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 1 -> 0
   */

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TimeTable timeTable0 = new TimeTable();
      GregorianCalendar mockGregorianCalendar0 = new GregorianCalendar((-77), (-77), (-77), (-77), 1040);
      CalDay calDay0 = new CalDay((GregorianCalendar) mockGregorianCalendar0);
      LinkedList<Appt> linkedList0 = calDay0.getAppts();
      GregorianCalendar mockGregorianCalendar1 = new GregorianCalendar((-3499), 1040, (-4451));
      // Undeclared exception!
  }

  //Test case number: 2
  /*
   * 9 covered goals:
   * Goal 1. edu.osu.cs362.TimeTable.<init>()V: root-Branch
   * Goal 2. Branch edu.osu.cs362.TimeTable.<init>()V: root-Branch in context: edu.osu.cs362.TimeTable:<init>()V
   * Goal 3. getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;_java.lang.NullPointerException_IMPLICIT
   * Goal 4. edu.osu.cs362.TimeTable.<init>()V: Line 27
   * Goal 5. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 40
   * Goal 6. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 43
   * Goal 7. [METHOD] edu.osu.cs362.TimeTable.<init>()V
   * Goal 8. [METHOD] edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 9. [METHODNOEX] edu.osu.cs362.TimeTable.<init>()V
   */

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TimeTable timeTable0 = new TimeTable();
      // Undeclared exception!
      try { 
        timeTable0.getApptRange((LinkedList<Appt>) null, (GregorianCalendar) null, (GregorianCalendar) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 3
  /*
   * 33 covered goals:
   * Goal 1. edu.osu.cs362.TimeTable.<init>()V: root-Branch
   * Goal 2. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I3 Branch 10 IFNULL L127 - false
   * Goal 3. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I5 Branch 11 IFNONNULL L127 - true
   * Goal 4. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I14 Branch 12 IFNE L130 - true
   * Goal 5. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I27 Branch 13 IF_ICMPGE L136 - false
   * Goal 6. Branch edu.osu.cs362.TimeTable.<init>()V: root-Branch in context: edu.osu.cs362.TimeTable:<init>()V
   * Goal 7. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I5 Branch 11 IFNONNULL L127 - true in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 8. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I3 Branch 10 IFNULL L127 - false in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 9. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I14 Branch 12 IFNE L130 - true in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 10. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I27 Branch 13 IF_ICMPGE L136 - false in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 11. deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;_java.lang.NullPointerException_IMPLICIT
   * Goal 12. edu.osu.cs362.TimeTable.<init>()V: Line 27
   * Goal 13. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 127
   * Goal 14. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 130
   * Goal 15. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 136
   * Goal 16. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 137
   * Goal 17. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 138
   * Goal 18. [METHOD] edu.osu.cs362.TimeTable.<init>()V
   * Goal 19. [METHOD] edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 20. [METHODNOEX] edu.osu.cs362.TimeTable.<init>()V
   * Goal 21. Weak Mutation 63: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:127 - ReplaceComparisonOperator = null -> != null
   * Goal 22. Weak Mutation 64: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:127 - ReplaceComparisonOperator != null -> = null
   * Goal 23. Weak Mutation 65: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:130 - ReplaceComparisonOperator != -> ==
   * Goal 24. Weak Mutation 66: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - ReplaceConstant - 0 -> 1
   * Goal 25. Weak Mutation 67: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - InsertUnaryOp Negation of i
   * Goal 26. Weak Mutation 68: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - InsertUnaryOp IINC 1 i
   * Goal 27. Weak Mutation 69: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - InsertUnaryOp IINC -1 i
   * Goal 28. Weak Mutation 70: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - ReplaceComparisonOperator >= -> -1
   * Goal 29. Weak Mutation 73: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:137 - InsertUnaryOp Negation of i
   * Goal 30. Weak Mutation 74: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:137 - InsertUnaryOp IINC 1 i
   * Goal 31. Weak Mutation 75: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:137 - InsertUnaryOp IINC -1 i
   * Goal 32. Weak Mutation 76: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:138 - ReplaceVariable tempAppt -> appt
   * Goal 33. Weak Mutation 77: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:138 - ReplaceVariable appt -> tempAppt
   */

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TimeTable timeTable0 = new TimeTable();
      LinkedList<Appt> linkedList0 = new LinkedList<Appt>();
      linkedList0.addFirst((Appt) null);
      Appt appt0 = new Appt(1, 1, 1, 1, 1, " ,|FMDW</|0^DmThU", "q_~R(W(5)+84X[");
      // Undeclared exception!
      try { 
        timeTable0.deleteAppt(linkedList0, appt0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 4
  /*
   * 41 covered goals:
   * Goal 1. edu.osu.cs362.TimeTable.<init>()V: root-Branch
   * Goal 2. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I3 Branch 10 IFNULL L127 - false
   * Goal 3. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I5 Branch 11 IFNONNULL L127 - true
   * Goal 4. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I14 Branch 12 IFNE L130 - true
   * Goal 5. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I27 Branch 13 IF_ICMPGE L136 - true
   * Goal 6. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I27 Branch 13 IF_ICMPGE L136 - false
   * Goal 7. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I40 Branch 14 IFEQ L138 - true
   * Goal 8. Branch edu.osu.cs362.TimeTable.<init>()V: root-Branch in context: edu.osu.cs362.TimeTable:<init>()V
   * Goal 9. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I5 Branch 11 IFNONNULL L127 - true in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 10. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I3 Branch 10 IFNULL L127 - false in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 11. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I14 Branch 12 IFNE L130 - true in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 12. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I27 Branch 13 IF_ICMPGE L136 - true in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 13. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I27 Branch 13 IF_ICMPGE L136 - false in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 14. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I40 Branch 14 IFEQ L138 - true in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 15. [Output]: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:Null
   * Goal 16. edu.osu.cs362.TimeTable.<init>()V: Line 27
   * Goal 17. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 127
   * Goal 18. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 130
   * Goal 19. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 136
   * Goal 20. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 137
   * Goal 21. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 138
   * Goal 22. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 144
   * Goal 23. [METHOD] edu.osu.cs362.TimeTable.<init>()V
   * Goal 24. [METHOD] edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 25. [METHODNOEX] edu.osu.cs362.TimeTable.<init>()V
   * Goal 26. [METHODNOEX] edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 27. Weak Mutation 63: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:127 - ReplaceComparisonOperator = null -> != null
   * Goal 28. Weak Mutation 64: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:127 - ReplaceComparisonOperator != null -> = null
   * Goal 29. Weak Mutation 65: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:130 - ReplaceComparisonOperator != -> ==
   * Goal 30. Weak Mutation 66: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - ReplaceConstant - 0 -> 1
   * Goal 31. Weak Mutation 67: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - InsertUnaryOp Negation of i
   * Goal 32. Weak Mutation 68: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - InsertUnaryOp IINC 1 i
   * Goal 33. Weak Mutation 69: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - InsertUnaryOp IINC -1 i
   * Goal 34. Weak Mutation 70: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - ReplaceComparisonOperator >= -> -1
   * Goal 35. Weak Mutation 71: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - ReplaceComparisonOperator >= -> >
   * Goal 36. Weak Mutation 73: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:137 - InsertUnaryOp Negation of i
   * Goal 37. Weak Mutation 74: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:137 - InsertUnaryOp IINC 1 i
   * Goal 38. Weak Mutation 75: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:137 - InsertUnaryOp IINC -1 i
   * Goal 39. Weak Mutation 76: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:138 - ReplaceVariable tempAppt -> appt
   * Goal 40. Weak Mutation 77: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:138 - ReplaceVariable appt -> tempAppt
   * Goal 41. Weak Mutation 78: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:138 - ReplaceComparisonOperator == -> !=
   */

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TimeTable timeTable0 = new TimeTable();
      GregorianCalendar mockGregorianCalendar0 = new GregorianCalendar();
      CalDay calDay0 = new CalDay((GregorianCalendar) mockGregorianCalendar0);
      LinkedList<Appt> linkedList0 = calDay0.appts;
      Appt appt0 = new Appt(2, 1, 1, 1, (-351), "\t", "\t");
      linkedList0.add(appt0);
      Appt appt1 = new Appt(1, 1, 1, 1, 1, "\t", "\t");
      timeTable0.deleteAppt(linkedList0, appt1);
      assertEquals(1, linkedList0.size());
      assertEquals(1, calDay0.getSizeAppts());
  }

  //Test case number: 5
  /*
   * 40 covered goals:
   * Goal 1. edu.osu.cs362.TimeTable.<init>()V: root-Branch
   * Goal 2. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I3 Branch 10 IFNULL L127 - false
   * Goal 3. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I5 Branch 11 IFNONNULL L127 - true
   * Goal 4. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I14 Branch 12 IFNE L130 - true
   * Goal 5. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I27 Branch 13 IF_ICMPGE L136 - false
   * Goal 6. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I40 Branch 14 IFEQ L138 - false
   * Goal 7. Branch edu.osu.cs362.TimeTable.<init>()V: root-Branch in context: edu.osu.cs362.TimeTable:<init>()V
   * Goal 8. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I5 Branch 11 IFNONNULL L127 - true in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 9. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I3 Branch 10 IFNULL L127 - false in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 10. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I14 Branch 12 IFNE L130 - true in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 11. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I27 Branch 13 IF_ICMPGE L136 - false in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 12. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I40 Branch 14 IFEQ L138 - false in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 13. [Output]: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:NonNull:java.util.LinkedList:size()I:Zero
   * Goal 14. edu.osu.cs362.TimeTable.<init>()V: Line 27
   * Goal 15. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 127
   * Goal 16. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 130
   * Goal 17. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 136
   * Goal 18. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 137
   * Goal 19. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 138
   * Goal 20. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 139
   * Goal 21. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 140
   * Goal 22. [METHOD] edu.osu.cs362.TimeTable.<init>()V
   * Goal 23. [METHOD] edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 24. [METHODNOEX] edu.osu.cs362.TimeTable.<init>()V
   * Goal 25. [METHODNOEX] edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 26. Weak Mutation 63: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:127 - ReplaceComparisonOperator = null -> != null
   * Goal 27. Weak Mutation 64: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:127 - ReplaceComparisonOperator != null -> = null
   * Goal 28. Weak Mutation 65: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:130 - ReplaceComparisonOperator != -> ==
   * Goal 29. Weak Mutation 66: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - ReplaceConstant - 0 -> 1
   * Goal 30. Weak Mutation 67: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - InsertUnaryOp Negation of i
   * Goal 31. Weak Mutation 68: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - InsertUnaryOp IINC 1 i
   * Goal 32. Weak Mutation 69: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - InsertUnaryOp IINC -1 i
   * Goal 33. Weak Mutation 70: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - ReplaceComparisonOperator >= -> -1
   * Goal 34. Weak Mutation 73: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:137 - InsertUnaryOp Negation of i
   * Goal 35. Weak Mutation 74: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:137 - InsertUnaryOp IINC 1 i
   * Goal 36. Weak Mutation 75: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:137 - InsertUnaryOp IINC -1 i
   * Goal 37. Weak Mutation 78: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:138 - ReplaceComparisonOperator == -> !=
   * Goal 38. Weak Mutation 79: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:139 - InsertUnaryOp Negation of i
   * Goal 39. Weak Mutation 80: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:139 - InsertUnaryOp IINC 1 i
   * Goal 40. Weak Mutation 81: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:139 - InsertUnaryOp IINC -1 i
   */

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TimeTable timeTable0 = new TimeTable();
      GregorianCalendar mockGregorianCalendar0 = new GregorianCalendar();
      CalDay calDay0 = new CalDay((GregorianCalendar) mockGregorianCalendar0);
      LinkedList<Appt> linkedList0 = calDay0.appts;
      Appt appt0 = new Appt(2, 1, 1, 1, (-351), "\t", "\t");
      linkedList0.add(appt0);
      timeTable0.deleteAppt(linkedList0, appt0);
      assertEquals(0, linkedList0.size());
      assertEquals(0, calDay0.getSizeAppts());
  }

  //Test case number: 6
  /*
   * 20 covered goals:
   * Goal 1. edu.osu.cs362.TimeTable.<init>()V: root-Branch
   * Goal 2. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I3 Branch 10 IFNULL L127 - false
   * Goal 3. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I5 Branch 11 IFNONNULL L127 - true
   * Goal 4. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I14 Branch 12 IFNE L130 - false
   * Goal 5. Branch edu.osu.cs362.TimeTable.<init>()V: root-Branch in context: edu.osu.cs362.TimeTable:<init>()V
   * Goal 6. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I5 Branch 11 IFNONNULL L127 - true in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 7. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I3 Branch 10 IFNULL L127 - false in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 8. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I14 Branch 12 IFNE L130 - false in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 9. [Output]: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:Null
   * Goal 10. edu.osu.cs362.TimeTable.<init>()V: Line 27
   * Goal 11. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 127
   * Goal 12. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 130
   * Goal 13. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 131
   * Goal 14. [METHOD] edu.osu.cs362.TimeTable.<init>()V
   * Goal 15. [METHOD] edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 16. [METHODNOEX] edu.osu.cs362.TimeTable.<init>()V
   * Goal 17. [METHODNOEX] edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 18. Weak Mutation 63: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:127 - ReplaceComparisonOperator = null -> != null
   * Goal 19. Weak Mutation 64: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:127 - ReplaceComparisonOperator != null -> = null
   * Goal 20. Weak Mutation 65: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:130 - ReplaceComparisonOperator != -> ==
   */

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TimeTable timeTable0 = new TimeTable();
      LinkedList<Appt> linkedList0 = new LinkedList<Appt>();
      Appt appt0 = new Appt(1, 0, 0, 0, 0, "\t --- ", "");
      LinkedList<Appt> linkedList1 = timeTable0.deleteAppt(linkedList0, appt0);
      assertNull(linkedList1);
  }

  //Test case number: 7
  /*
   * 16 covered goals:
   * Goal 1. edu.osu.cs362.TimeTable.<init>()V: root-Branch
   * Goal 2. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I3 Branch 10 IFNULL L127 - false
   * Goal 3. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I5 Branch 11 IFNONNULL L127 - false
   * Goal 4. Branch edu.osu.cs362.TimeTable.<init>()V: root-Branch in context: edu.osu.cs362.TimeTable:<init>()V
   * Goal 5. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I5 Branch 11 IFNONNULL L127 - false in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 6. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I3 Branch 10 IFNULL L127 - false in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 7. [Output]: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:Null
   * Goal 8. edu.osu.cs362.TimeTable.<init>()V: Line 27
   * Goal 9. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 127
   * Goal 10. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 128
   * Goal 11. [METHOD] edu.osu.cs362.TimeTable.<init>()V
   * Goal 12. [METHOD] edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 13. [METHODNOEX] edu.osu.cs362.TimeTable.<init>()V
   * Goal 14. [METHODNOEX] edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 15. Weak Mutation 63: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:127 - ReplaceComparisonOperator = null -> != null
   * Goal 16. Weak Mutation 64: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:127 - ReplaceComparisonOperator != null -> = null
   */

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TimeTable timeTable0 = new TimeTable();
      LinkedList<Appt> linkedList0 = new LinkedList<Appt>();
      LinkedList<Appt> linkedList1 = timeTable0.deleteAppt(linkedList0, (Appt) null);
      assertNull(linkedList1);
  }

  //Test case number: 8
  /*
   * 13 covered goals:
   * Goal 1. edu.osu.cs362.TimeTable.<init>()V: root-Branch
   * Goal 2. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I3 Branch 10 IFNULL L127 - true
   * Goal 3. Branch edu.osu.cs362.TimeTable.<init>()V: root-Branch in context: edu.osu.cs362.TimeTable:<init>()V
   * Goal 4. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I3 Branch 10 IFNULL L127 - true in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 5. [Output]: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:Null
   * Goal 6. edu.osu.cs362.TimeTable.<init>()V: Line 27
   * Goal 7. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 127
   * Goal 8. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 128
   * Goal 9. [METHOD] edu.osu.cs362.TimeTable.<init>()V
   * Goal 10. [METHOD] edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 11. [METHODNOEX] edu.osu.cs362.TimeTable.<init>()V
   * Goal 12. [METHODNOEX] edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 13. Weak Mutation 63: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:127 - ReplaceComparisonOperator = null -> != null
   */

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TimeTable timeTable0 = new TimeTable();
      Appt appt0 = new Appt(5, 5, 690, 5, 690, "am", "am");
      LinkedList<Appt> linkedList0 = timeTable0.deleteAppt((LinkedList<Appt>) null, appt0);
      assertNull(linkedList0);
  }

  //Test case number: 9
  /*
   * 109 covered goals:
   * Goal 1. edu.osu.cs362.TimeTable.<init>()V: root-Branch
   * Goal 2. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I11 Branch 1 IFNE L43 - true
   * Goal 3. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I43 Branch 2 IFEQ L51 - true
   * Goal 4. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I43 Branch 2 IFEQ L51 - false
   * Goal 5. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I70 Branch 3 IF_ICMPGE L57 - true
   * Goal 6. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I70 Branch 3 IF_ICMPGE L57 - false
   * Goal 7. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I82 Branch 4 IFNE L59 - true
   * Goal 8. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I110 Branch 5 IFEQ L70 - true
   * Goal 9. edu.osu.cs362.TimeTable.getApptOccurences(Ledu/osu/cs362/Appt;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I11 Branch 7 IFNE L98 - true
   * Goal 10. edu.osu.cs362.TimeTable.getApptOccurences(Ledu/osu/cs362/Appt;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I54 Branch 8 IFNE L109 - true
   * Goal 11. edu.osu.cs362.TimeTable.getApptOccurences(Ledu/osu/cs362/Appt;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I64 Branch 9 IFNE L115 - true
   * Goal 12. Branch edu.osu.cs362.TimeTable.<init>()V: root-Branch in context: edu.osu.cs362.TimeTable:<init>()V
   * Goal 13. Branch edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I11 Branch 1 IFNE L43 - true in context: edu.osu.cs362.TimeTable:getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 14. Branch edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I43 Branch 2 IFEQ L51 - true in context: edu.osu.cs362.TimeTable:getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 15. Branch edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I43 Branch 2 IFEQ L51 - false in context: edu.osu.cs362.TimeTable:getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 16. Branch edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I70 Branch 3 IF_ICMPGE L57 - false in context: edu.osu.cs362.TimeTable:getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 17. Branch edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I70 Branch 3 IF_ICMPGE L57 - true in context: edu.osu.cs362.TimeTable:getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 18. Branch edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I82 Branch 4 IFNE L59 - true in context: edu.osu.cs362.TimeTable:getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 19. Branch edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I110 Branch 5 IFEQ L70 - true in context: edu.osu.cs362.TimeTable:getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 20. Branch edu.osu.cs362.TimeTable.getApptOccurences(Ledu/osu/cs362/Appt;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I11 Branch 7 IFNE L98 - true in context: 
   * Goal 21. Branch edu.osu.cs362.TimeTable.getApptOccurences(Ledu/osu/cs362/Appt;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I54 Branch 8 IFNE L109 - true in context: 
   * Goal 22. Branch edu.osu.cs362.TimeTable.getApptOccurences(Ledu/osu/cs362/Appt;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I64 Branch 9 IFNE L115 - true in context: 
   * Goal 23. [Output]: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:NonNull:java.util.LinkedList:size()I:Positive
   * Goal 24. edu.osu.cs362.TimeTable.<init>()V: Line 27
   * Goal 25. edu.osu.cs362.TimeTable.getApptOccurences(Ledu/osu/cs362/Appt;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 95
   * Goal 26. edu.osu.cs362.TimeTable.getApptOccurences(Ledu/osu/cs362/Appt;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 98
   * Goal 27. edu.osu.cs362.TimeTable.getApptOccurences(Ledu/osu/cs362/Appt;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 103
   * Goal 28. edu.osu.cs362.TimeTable.getApptOccurences(Ledu/osu/cs362/Appt;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 104
   * Goal 29. edu.osu.cs362.TimeTable.getApptOccurences(Ledu/osu/cs362/Appt;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 105
   * Goal 30. edu.osu.cs362.TimeTable.getApptOccurences(Ledu/osu/cs362/Appt;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 109
   * Goal 31. edu.osu.cs362.TimeTable.getApptOccurences(Ledu/osu/cs362/Appt;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 115
   * Goal 32. edu.osu.cs362.TimeTable.getApptOccurences(Ledu/osu/cs362/Appt;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 119
   * Goal 33. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 40
   * Goal 34. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 43
   * Goal 35. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 50
   * Goal 36. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 51
   * Goal 37. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 52
   * Goal 38. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 53
   * Goal 39. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 57
   * Goal 40. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 58
   * Goal 41. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 59
   * Goal 42. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 61
   * Goal 43. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 67
   * Goal 44. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 68
   * Goal 45. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 69
   * Goal 46. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 70
   * Goal 47. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 84
   * Goal 48. [METHOD] edu.osu.cs362.TimeTable.<init>()V
   * Goal 49. [METHOD] edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 50. [METHODNOEX] edu.osu.cs362.TimeTable.<init>()V
   * Goal 51. [METHODNOEX] edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 52. Weak Mutation 0: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:43 - ReplaceVariable firstDay -> lastDay
   * Goal 53. Weak Mutation 1: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:43 - ReplaceVariable lastDay -> firstDay
   * Goal 54. Weak Mutation 2: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:43 - ReplaceComparisonOperator != -> ==
   * Goal 55. Weak Mutation 5: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:50 - ReplaceVariable firstDay -> lastDay
   * Goal 56. Weak Mutation 6: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:51 - ReplaceVariable nextDay -> firstDay
   * Goal 57. Weak Mutation 7: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:51 - ReplaceVariable nextDay -> lastDay
   * Goal 58. Weak Mutation 8: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:51 - ReplaceVariable lastDay -> firstDay
   * Goal 59. Weak Mutation 9: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:51 - ReplaceVariable lastDay -> nextDay
   * Goal 60. Weak Mutation 10: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:51 - ReplaceComparisonOperator == -> !=
   * Goal 61. Weak Mutation 11: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:52 - ReplaceVariable calDays -> appts
   * Goal 62. Weak Mutation 12: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:52 - ReplaceVariable nextDay -> firstDay
   * Goal 63. Weak Mutation 13: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:52 - ReplaceVariable nextDay -> lastDay
   * Goal 64. Weak Mutation 14: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceVariable nextDay -> firstDay
   * Goal 65. Weak Mutation 15: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceVariable nextDay -> lastDay
   * Goal 66. Weak Mutation 16: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceVariable nextDay -> firstDay
   * Goal 67. Weak Mutation 17: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceVariable nextDay -> lastDay
   * Goal 68. Weak Mutation 18: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 5 -> 0
   * Goal 69. Weak Mutation 19: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 5 -> 1
   * Goal 70. Weak Mutation 20: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 5 -> -1
   * Goal 71. Weak Mutation 21: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 5 -> 4
   * Goal 72. Weak Mutation 22: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 5 -> 6
   * Goal 73. Weak Mutation 23: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 1 -> 0
   * Goal 74. Weak Mutation 24: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:57 - ReplaceConstant - 0 -> 1
   * Goal 75. Weak Mutation 25: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:57 - InsertUnaryOp Negation of i
   * Goal 76. Weak Mutation 26: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:57 - InsertUnaryOp IINC 1 i
   * Goal 77. Weak Mutation 27: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:57 - InsertUnaryOp IINC -1 i
   * Goal 78. Weak Mutation 28: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:57 - ReplaceVariable appts -> calDays
   * Goal 79. Weak Mutation 29: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:57 - ReplaceComparisonOperator >= -> -1
   * Goal 80. Weak Mutation 30: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:57 - ReplaceComparisonOperator >= -> >
   * Goal 81. Weak Mutation 32: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:58 - ReplaceVariable appts -> calDays
   * Goal 82. Weak Mutation 33: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:58 - InsertUnaryOp Negation of i
   * Goal 83. Weak Mutation 34: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:58 - InsertUnaryOp IINC 1 i
   * Goal 84. Weak Mutation 35: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:58 - InsertUnaryOp IINC -1 i
   * Goal 85. Weak Mutation 36: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:59 - ReplaceComparisonOperator != -> ==
   * Goal 86. Weak Mutation 37: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:61 - ReplaceVariable firstDay -> nextDay
   * Goal 87. Weak Mutation 38: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:61 - ReplaceVariable firstDay -> lastDay
   * Goal 88. Weak Mutation 39: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:61 - ReplaceVariable lastDay -> firstDay
   * Goal 89. Weak Mutation 40: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:61 - ReplaceVariable lastDay -> nextDay
   * Goal 90. Weak Mutation 41: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:67 - ReplaceConstant - 0 -> 1
   * Goal 91. Weak Mutation 42: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:68 - ReplaceVariable firstDay -> nextDay
   * Goal 92. Weak Mutation 43: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:68 - ReplaceVariable firstDay -> lastDay
   * Goal 93. Weak Mutation 44: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:69 - ReplaceVariable apptOccursOnDays -> calDays
   * Goal 94. Weak Mutation 45: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:69 - ReplaceVariable apptOccursOnDays -> appts
   * Goal 95. Weak Mutation 46: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:70 - ReplaceComparisonOperator == -> !=
   * Goal 96. Weak Mutation 47: edu.osu.cs362.TimeTable.getApptOccurences(Ledu/osu/cs362/Appt;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:98 - ReplaceVariable firstDay -> lastDay
   * Goal 97. Weak Mutation 48: edu.osu.cs362.TimeTable.getApptOccurences(Ledu/osu/cs362/Appt;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:98 - ReplaceVariable lastDay -> firstDay
   * Goal 98. Weak Mutation 49: edu.osu.cs362.TimeTable.getApptOccurences(Ledu/osu/cs362/Appt;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:98 - ReplaceComparisonOperator != -> ==
   * Goal 99. Weak Mutation 50: edu.osu.cs362.TimeTable.getApptOccurences(Ledu/osu/cs362/Appt;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:105 - ReplaceComparisonOperator == -> !=
   * Goal 100. Weak Mutation 51: edu.osu.cs362.TimeTable.getApptOccurences(Ledu/osu/cs362/Appt;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:109 - ReplaceVariable occurrenceDay -> firstDay
   * Goal 101. Weak Mutation 52: edu.osu.cs362.TimeTable.getApptOccurences(Ledu/osu/cs362/Appt;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:109 - ReplaceVariable occurrenceDay -> lastDay
   * Goal 102. Weak Mutation 53: edu.osu.cs362.TimeTable.getApptOccurences(Ledu/osu/cs362/Appt;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:109 - ReplaceVariable lastDay -> firstDay
   * Goal 103. Weak Mutation 54: edu.osu.cs362.TimeTable.getApptOccurences(Ledu/osu/cs362/Appt;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:109 - ReplaceVariable lastDay -> occurrenceDay
   * Goal 104. Weak Mutation 55: edu.osu.cs362.TimeTable.getApptOccurences(Ledu/osu/cs362/Appt;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:109 - ReplaceComparisonOperator != -> ==
   * Goal 105. Weak Mutation 56: edu.osu.cs362.TimeTable.getApptOccurences(Ledu/osu/cs362/Appt;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:115 - ReplaceVariable occurrenceDay -> firstDay
   * Goal 106. Weak Mutation 57: edu.osu.cs362.TimeTable.getApptOccurences(Ledu/osu/cs362/Appt;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:115 - ReplaceVariable occurrenceDay -> lastDay
   * Goal 107. Weak Mutation 58: edu.osu.cs362.TimeTable.getApptOccurences(Ledu/osu/cs362/Appt;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:115 - ReplaceVariable firstDay -> lastDay
   * Goal 108. Weak Mutation 59: edu.osu.cs362.TimeTable.getApptOccurences(Ledu/osu/cs362/Appt;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:115 - ReplaceVariable firstDay -> occurrenceDay
   * Goal 109. Weak Mutation 60: edu.osu.cs362.TimeTable.getApptOccurences(Ledu/osu/cs362/Appt;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:115 - ReplaceComparisonOperator != -> ==
   */



  //Test case number: 10
  /*
   * 64 covered goals:
   * Goal 1. edu.osu.cs362.TimeTable.<init>()V: root-Branch
   * Goal 2. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I11 Branch 1 IFNE L43 - true
   * Goal 3. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I43 Branch 2 IFEQ L51 - true
   * Goal 4. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I43 Branch 2 IFEQ L51 - false
   * Goal 5. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I70 Branch 3 IF_ICMPGE L57 - true
   * Goal 6. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I70 Branch 3 IF_ICMPGE L57 - false
   * Goal 7. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I82 Branch 4 IFNE L59 - false
   * Goal 8. Branch edu.osu.cs362.TimeTable.<init>()V: root-Branch in context: edu.osu.cs362.TimeTable:<init>()V
   * Goal 9. Branch edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I11 Branch 1 IFNE L43 - true in context: edu.osu.cs362.TimeTable:getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 10. Branch edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I43 Branch 2 IFEQ L51 - true in context: edu.osu.cs362.TimeTable:getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 11. Branch edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I43 Branch 2 IFEQ L51 - false in context: edu.osu.cs362.TimeTable:getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 12. Branch edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I70 Branch 3 IF_ICMPGE L57 - false in context: edu.osu.cs362.TimeTable:getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 13. Branch edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I70 Branch 3 IF_ICMPGE L57 - true in context: edu.osu.cs362.TimeTable:getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 14. Branch edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I82 Branch 4 IFNE L59 - false in context: edu.osu.cs362.TimeTable:getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 15. [Output]: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:NonNull:java.util.LinkedList:size()I:Positive
   * Goal 16. edu.osu.cs362.TimeTable.<init>()V: Line 27
   * Goal 17. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 40
   * Goal 18. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 43
   * Goal 19. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 50
   * Goal 20. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 51
   * Goal 21. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 52
   * Goal 22. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 53
   * Goal 23. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 57
   * Goal 24. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 58
   * Goal 25. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 59
   * Goal 26. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 84
   * Goal 27. [METHOD] edu.osu.cs362.TimeTable.<init>()V
   * Goal 28. [METHOD] edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 29. [METHODNOEX] edu.osu.cs362.TimeTable.<init>()V
   * Goal 30. [METHODNOEX] edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 31. Weak Mutation 0: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:43 - ReplaceVariable firstDay -> lastDay
   * Goal 32. Weak Mutation 1: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:43 - ReplaceVariable lastDay -> firstDay
   * Goal 33. Weak Mutation 2: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:43 - ReplaceComparisonOperator != -> ==
   * Goal 34. Weak Mutation 5: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:50 - ReplaceVariable firstDay -> lastDay
   * Goal 35. Weak Mutation 6: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:51 - ReplaceVariable nextDay -> firstDay
   * Goal 36. Weak Mutation 7: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:51 - ReplaceVariable nextDay -> lastDay
   * Goal 37. Weak Mutation 8: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:51 - ReplaceVariable lastDay -> firstDay
   * Goal 38. Weak Mutation 9: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:51 - ReplaceVariable lastDay -> nextDay
   * Goal 39. Weak Mutation 10: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:51 - ReplaceComparisonOperator == -> !=
   * Goal 40. Weak Mutation 11: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:52 - ReplaceVariable calDays -> appts
   * Goal 41. Weak Mutation 12: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:52 - ReplaceVariable nextDay -> firstDay
   * Goal 42. Weak Mutation 13: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:52 - ReplaceVariable nextDay -> lastDay
   * Goal 43. Weak Mutation 14: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceVariable nextDay -> firstDay
   * Goal 44. Weak Mutation 15: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceVariable nextDay -> lastDay
   * Goal 45. Weak Mutation 16: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceVariable nextDay -> firstDay
   * Goal 46. Weak Mutation 17: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceVariable nextDay -> lastDay
   * Goal 47. Weak Mutation 18: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 5 -> 0
   * Goal 48. Weak Mutation 19: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 5 -> 1
   * Goal 49. Weak Mutation 20: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 5 -> -1
   * Goal 50. Weak Mutation 21: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 5 -> 4
   * Goal 51. Weak Mutation 22: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 5 -> 6
   * Goal 52. Weak Mutation 23: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 1 -> 0
   * Goal 53. Weak Mutation 24: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:57 - ReplaceConstant - 0 -> 1
   * Goal 54. Weak Mutation 25: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:57 - InsertUnaryOp Negation of i
   * Goal 55. Weak Mutation 26: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:57 - InsertUnaryOp IINC 1 i
   * Goal 56. Weak Mutation 27: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:57 - InsertUnaryOp IINC -1 i
   * Goal 57. Weak Mutation 28: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:57 - ReplaceVariable appts -> calDays
   * Goal 58. Weak Mutation 29: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:57 - ReplaceComparisonOperator >= -> -1
   * Goal 59. Weak Mutation 30: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:57 - ReplaceComparisonOperator >= -> >
   * Goal 60. Weak Mutation 32: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:58 - ReplaceVariable appts -> calDays
   * Goal 61. Weak Mutation 33: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:58 - InsertUnaryOp Negation of i
   * Goal 62. Weak Mutation 34: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:58 - InsertUnaryOp IINC 1 i
   * Goal 63. Weak Mutation 35: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:58 - InsertUnaryOp IINC -1 i
   * Goal 64. Weak Mutation 36: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:59 - ReplaceComparisonOperator != -> ==
   */


  //Test case number: 11
  /*
   * 15 covered goals:
   * Goal 1. edu.osu.cs362.TimeTable.<init>()V: root-Branch
   * Goal 2. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I11 Branch 1 IFNE L43 - false
   * Goal 3. Branch edu.osu.cs362.TimeTable.<init>()V: root-Branch in context: edu.osu.cs362.TimeTable:<init>()V
   * Goal 4. Branch edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I11 Branch 1 IFNE L43 - false in context: edu.osu.cs362.TimeTable:getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 5. getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;_java.lang.IllegalArgumentException_EXPLICIT
   * Goal 6. edu.osu.cs362.TimeTable.<init>()V: Line 27
   * Goal 7. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 40
   * Goal 8. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 43
   * Goal 9. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 44
   * Goal 10. [METHOD] edu.osu.cs362.TimeTable.<init>()V
   * Goal 11. [METHOD] edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 12. [METHODNOEX] edu.osu.cs362.TimeTable.<init>()V
   * Goal 13. Weak Mutation 2: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:43 - ReplaceComparisonOperator != -> ==
   * Goal 14. Weak Mutation 3: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:44 - ReplaceConstant - Second date specified is not before the first date specified. -> 
   * Goal 15. Weak Mutation 4: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:44 - ReplaceComparisonOperator == -> !=
   */

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TimeTable timeTable0 = new TimeTable();
      GregorianCalendar mockGregorianCalendar0 = new GregorianCalendar();
      CalDay calDay0 = new CalDay((GregorianCalendar) mockGregorianCalendar0);
      LinkedList<Appt> linkedList0 = calDay0.appts;
      // Undeclared exception!
      try { 
        timeTable0.getApptRange(linkedList0, mockGregorianCalendar0, mockGregorianCalendar0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Second date specified is not before the first date specified.
         //
      }
  }
}
